services:
  - type: web
    name: web-health-demo
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run server
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health

